name: Workflow testing

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  experimental-greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: echo "Hello Desislava"
      - name: Show directory before checkout
        run: ls -l
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show directory after checkout
        run: ls -l
